# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=10)),
                ('imageUrl', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('updated_at', models.DateTimeField(verbose_name='date created')),
                ('bands', models.ManyToManyField(to='bandsApp.Band')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('creditCard', models.CharField(max_length=16, null=True)),
                ('shipping_street_address', models.CharField(max_length=255, null=True)),
                ('shipping_city', models.CharField(max_length=255, null=True)),
                ('shipping_state', models.CharField(max_length=2, null=True)),
                ('shipping_country', models.CharField(max_length=50, null=True)),
                ('billing_street_address', models.CharField(max_length=255, null=True)),
                ('billing_city', models.CharField(max_length=255, null=True)),
                ('billing_state', models.CharField(max_length=2, null=True)),
                ('billing_country', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bandsApp.User'),
        ),
        migrations.AddField(
            model_name='band',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='bandsApp.Vendor'),
        ),
    ]
