# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendorType',
            field=models.CharField(default='artist', max_length=20),
            preserve_default=False,
        ),
    ]
