# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-21 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandsApp', '0002_vendor_vendortype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bandsApp.User'),
        ),
    ]
