# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandsApp', '0002_vendor_vendortype'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='imageUrl',
            field=models.CharField(default='abc', max_length=255),
            preserve_default=False,
        ),
    ]
