# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandsApp', '0003_vendor_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(verbose_name='date updated'),
        ),
    ]
