# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandsApp', '0006_auto_20171021_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
