# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandsApp', '0007_order_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
