# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandsApp', '0003_auto_20171021_2051'),
        ('bandsApp', '0008_band_price'),
    ]

    operations = [
    ]
