# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandsApp', '0009_merge_20171022_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bandsApp.User'),
        ),
    ]
